# A Python like list with the names for each parameter.
# Must match the names defined in the .stan model file!
names: ["h", "Omega_m", "M"]

# A Python like list with the labels for each parameter.
# If empty the names will be used instead.
# These will be rendered on the plots and support latex, however, you have to escape the blackslashes.
# (e.g.: write \\alpha instead of \alpha for the character α)
labels: ["h", "\\Omega_m", "M"]

# Initial condition for each parameter, for each chain.
# This will run an arbitrary Python command (so be careful!).
# The most relevant initial conditions are:
# - gauss(mu, sigma)
# - uniform(a, b)
# - float(a)
initial:
  h: gauss(0.7, 0.15)
  Omega_m: gauss(0.284, 0.1)
  M: gauss(0, 5)

# Line markers to show rendered in the plots.
# These can be used to represent the true or expected values.
# Leave empty to have no markers or suppress an entry to have no marker associated with that parameter.
markers:
  h: 0.7
  Omega_m: 0.284
  M: 0

# Number of steps to sample the posterior distribution, after the warmup.
samples: 750

# Number of steps to warmup each chain.
# These samples will be discarded.
warmup: 150

# Number of chains to run.
# Will run in parallel, provided that there are enough threads to do so.
# Leave empty for a single chain.
# Keep in mind that each chain will do a total number of steps = warmup + samples.
chains: 4
